# Generated by Django 4.1.2 on 2022-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img_href', models.URLField(default='')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
