# Generated by Django 4.1.2 on 2022-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='CheckBox',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='Selection',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
