# Generated by Django 4.1.2 on 2022-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_text_checkbox_text_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='CheckBox',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='img_href',
            field=models.CharField(default='', max_length=500),
        ),
    ]
