# Generated by Django 4.1.2 on 2022-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_text_checkbox_alter_text_img_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='Selection',
            field=models.CharField(max_length=256),
        ),
    ]
